source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

def shared_pods
    pod 'RxSwift', '~> 2.0'
    pod 'RxCache', :path => '../'
end

def shared_pods_test
    pod 'RxSwift', '~> 2.0'
    pod 'Nimble', '~> 3.1.0'
    pod 'RxCache', :path => '../'
end

target 'RxCacheIOS' do
    platform :ios, '8.0'
    shared_pods
end

target 'RxCacheMac' do
    platform :osx, '10.9'
    shared_pods
end

target 'RxCacheWatchOS' do
    platform :watchos, '2.0'
    shared_pods
end


target 'RxCacheIOSTests' do
    platform :ios, '8.0'
    shared_pods_test
end

target 'RxCacheMacTests' do
    platform :osx, '10.9'
    shared_pods_test
end
