source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RxCache' do
    pod 'RxSwift', '~> 2.0'
end

target 'RxCacheTests' do
    pod 'RxSwift', '~> 2.0'
    pod 'Nimble', '~> 4.0.0'
    pod 'ObjectMapper', '~> 1.1'
    pod 'Gloss', '~> 0.7'
end