source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

def shared_pods
    pod 'ObjectMapper', '~> 2.0'
    pod 'RxSwift', '>= 3.0.0-beta.1'
    pod 'Gloss', '~> 1.0'
end

target 'RxCache' do
    shared_pods
end

target 'RxCacheTests' do
    shared_pods
    pod 'Nimble', '~> 5.0.0'
end
