source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

def shared_pods
    #    pod 'RxCache', '~> 0.1.2'
    pod 'ObjectMapper', '~> 2.0'
    pod 'RxSwift', '>= 3.0.0-beta.1'
    pod 'Gloss', '~> 1.0'
end

target 'iOS' do
    platform :ios, '9.0'
    shared_pods
end

target 'OSX' do
    platform :osx, '11.0'
    shared_pods
end
