source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

def shared_pods
    pod 'RxSwift', '~> 2.0'
    pod 'RxCache', '~> 0.1.1'
    pod 'ObjectMapper', '~> 1.1'
    pod 'Gloss', '~> 0.7'
    pod 'Moya/RxSwift'
end

target 'iOS' do
    platform :ios, '8.0'
    shared_pods
end

target 'OSX' do
    platform :osx, '10.9'
    shared_pods
end