source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

def shared_pods
    pod 'RxSwift', '~> 4.0'
    pod 'Gloss', '~> 2.0'
    pod 'ObjectMapper', '~> 3.1'
end

target 'RxCache' do
    shared_pods
end

target 'RxCacheTests' do
    shared_pods
    pod 'Nimble', '~> 6.0.0'
end
